import type { Metadata } from "next";

import Footer from "@/components/layout/footer";

import { FONT_MONO, FONT_SANS, FONT_SERIF } from "@/fonts";

import WithCanvas from "@/components/layout/with-canvas";
import DitheringCanvas from "@/components/models/dithering-canvas";
import Header from "@/components/layout/header";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${FONT_SERIF.variable} ${FONT_SANS.variable} ${FONT_MONO.variable} bg-deep-black text-foreground-dark font-mono transition-colors`}
      >
        <WithCanvas
          canvas={
            <>
              <DitheringCanvas
                className="h-full"
                colorBack="#0d0f00"
                colorFront="#770b03"
              />
            </>
          }
        >
          <div className="flex min-h-screen flex-col justify-between">
            <div className="mb-18">
              <Header />

              <main>{children}</main>
            </div>

            <Footer />
          </div>
        </WithCanvas>
      </body>
    </html>
  );
}
